---
upload_path: "/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
collections:
  _projects:
    default_front_matter_template: projects
  _people:
    default_front_matter_template: people
  _posts:
    default_front_matter_template: posts
