---
upload_path: "/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
collections:
  _publications:
    default_front_matter_template: publication
  _projects:
    default_front_matter_template: project
  _people:
    default_front_matter_template: person
  _posts:
    default_front_matter_template: post
