---
upload_path: "/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
collections:
  _posts:
    default_front_matter_template: post
  _projects:
    default_front_matter_template: project
  _people:
    default_front_matter_template: person
